package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunGeneratesProductTree(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "bitbucket"); err != nil {
		t.Fatalf("run: %v", err)
	}
	// The root page and a known nested command page must exist.
	for _, rel := range []string{
		"bitbucket/atl-bb.md",
		"bitbucket/atl-bb_repo_list.md",
		"bitbucket/atl-bb_status.md",
	} {
		if _, err := os.Stat(filepath.Join(dir, rel)); err != nil {
			t.Errorf("expected generated doc %q: %v", rel, err)
		}
	}
}

func TestRunAllProducts(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "all"); err != nil {
		t.Fatalf("run all: %v", err)
	}
	for _, rel := range []string{
		"jira/atl-jira.md",
		"confluence/atl-conf.md",
		"bitbucket/atl-bb.md",
	} {
		if _, err := os.Stat(filepath.Join(dir, rel)); err != nil {
			t.Errorf("expected generated doc %q: %v", rel, err)
		}
	}
}

func TestSelectBuildersUnknownProduct(t *testing.T) {
	if _, err := selectBuilders("github"); err == nil {
		t.Fatal("expected an error for an unknown product")
	}
}

func TestRunDisablesAutoGenTag(t *testing.T) {
	dir := t.TempDir()
	if err := run(dir, "bitbucket"); err != nil {
		t.Fatalf("run: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "bitbucket", "atl-bb.md"))
	if err != nil {
		t.Fatalf("read root doc: %v", err)
	}
	// DisableAutoGenTag must suppress the "Auto generated by ..." footer so the
	// committed docs stay reproducible.
	if strings.Contains(string(body), "Auto generated") {
		t.Errorf("root doc carries an auto-gen footer:\n%s", string(body))
	}
}
